spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1111
    url: jdbc:postgresql://localhost:5433/new_db
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: postgresql
  sql:
    init:
      mode: always
      platform: postgres
      continue-on-error: false
server:
  port: 8081